-- ============================================================
-- FCT-SEEK: SCRIPT PARA PGADMIN (v2 - Hash corregido)
-- ============================================================
-- INSTRUCCIONES:
-- 1. En pgAdmin, borra la BD "fctseek" si existe (click derecho → Delete)
-- 2. Crea una nueva BD llamada "fctseek" (click derecho en Databases → Create)
-- 3. Click derecho en "fctseek" → Query Tool
-- 4. Abre este archivo y ejecuta (F5)
-- ============================================================

-- ============================================================
-- TABLAS
-- ============================================================

CREATE TABLE departamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(10) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nif VARCHAR(15) NOT NULL UNIQUE,
    nombre VARCHAR(50) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL,
    departamento_id BIGINT REFERENCES departamentos(id),
    activo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE cursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL UNIQUE,
    siglas VARCHAR(10) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    grado VARCHAR(20) NOT NULL,
    departamento_id BIGINT NOT NULL REFERENCES departamentos(id),
    activo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE empresas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cif VARCHAR(15) UNIQUE,
    nombre VARCHAR(150) NOT NULL,
    direccion VARCHAR(200),
    ciudad VARCHAR(100) NOT NULL,
    codigo_postal VARCHAR(10),
    telefono VARCHAR(20),
    email VARCHAR(150),
    web VARCHAR(200),
    persona_contacto VARCHAR(100),
    telefono_contacto VARCHAR(20),
    email_contacto VARCHAR(150),
    descripcion TEXT,
    activa BOOLEAN NOT NULL DEFAULT true,
    created_by BIGINT REFERENCES usuarios(id),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE empresa_cursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL REFERENCES empresas(id),
    curso_id BIGINT NOT NULL REFERENCES cursos(id),
    created_at TIMESTAMP(6),
    UNIQUE(empresa_id, curso_id)
);

CREATE TABLE empresa_contactada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL REFERENCES empresas(id),
    departamento_id BIGINT NOT NULL REFERENCES departamentos(id),
    profesor_id BIGINT NOT NULL REFERENCES usuarios(id),
    fecha DATE NOT NULL,
    notas TEXT,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    UNIQUE(empresa_id, departamento_id)
);

CREATE TABLE comentarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL REFERENCES empresas(id),
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
    texto TEXT NOT NULL,
    es_privado BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE valoraciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL REFERENCES empresas(id),
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
    puntuacion INTEGER NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    UNIQUE(empresa_id, usuario_id)
);

CREATE TABLE favoritos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
    empresa_id BIGINT NOT NULL REFERENCES empresas(id),
    created_at TIMESTAMP(6),
    UNIQUE(usuario_id, empresa_id)
);

CREATE TABLE listas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    es_favoritos BOOLEAN NOT NULL DEFAULT false,
    usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE lista_empresas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lista_id BIGINT NOT NULL REFERENCES listas(id),
    empresa_id BIGINT NOT NULL REFERENCES empresas(id),
    notas TEXT,
    created_at TIMESTAMP(6),
    UNIQUE(lista_id, empresa_id)
);

CREATE TABLE plazas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL REFERENCES empresas(id),
    departamento_id BIGINT NOT NULL REFERENCES departamentos(id),
    curso_id BIGINT REFERENCES cursos(id),
    cantidad INTEGER NOT NULL,
    es_general BOOLEAN NOT NULL DEFAULT false,
    curso_academico VARCHAR(9) NOT NULL,
    created_by BIGINT REFERENCES usuarios(id),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    UNIQUE(empresa_id, departamento_id, curso_id, curso_academico)
);

CREATE TABLE reservas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plaza_id BIGINT NOT NULL REFERENCES plazas(id),
    curso_id BIGINT NOT NULL REFERENCES cursos(id),
    profesor_id BIGINT NOT NULL REFERENCES usuarios(id),
    cantidad INTEGER NOT NULL,
    clase VARCHAR(10),
    estado VARCHAR(20) NOT NULL,
    notas TEXT,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);


-- ============================================================
-- ÍNDICES
-- ============================================================

CREATE INDEX idx_comentarios_empresa_id ON comentarios(empresa_id);
CREATE INDEX idx_comentarios_usuario_id ON comentarios(usuario_id);
CREATE INDEX idx_cursos_departamento_id ON cursos(departamento_id);
CREATE INDEX idx_empresa_contactada_empresa_id ON empresa_contactada(empresa_id);
CREATE INDEX idx_empresa_contactada_departamento_id ON empresa_contactada(departamento_id);
CREATE INDEX idx_empresa_contactada_profesor_id ON empresa_contactada(profesor_id);
CREATE INDEX idx_empresa_cursos_empresa_id ON empresa_cursos(empresa_id);
CREATE INDEX idx_empresa_cursos_curso_id ON empresa_cursos(curso_id);
CREATE INDEX idx_empresas_created_by ON empresas(created_by);
CREATE INDEX idx_favoritos_empresa_id ON favoritos(empresa_id);
CREATE INDEX idx_favoritos_usuario_id ON favoritos(usuario_id);
CREATE INDEX idx_lista_empresas_lista_id ON lista_empresas(lista_id);
CREATE INDEX idx_lista_empresas_empresa_id ON lista_empresas(empresa_id);
CREATE INDEX idx_listas_usuario_id ON listas(usuario_id);
CREATE INDEX idx_plazas_empresa_id ON plazas(empresa_id);
CREATE INDEX idx_plazas_departamento_id ON plazas(departamento_id);
CREATE INDEX idx_plazas_curso_id ON plazas(curso_id);
CREATE INDEX idx_plazas_created_by ON plazas(created_by);
CREATE INDEX idx_reservas_plaza_id ON reservas(plaza_id);
CREATE INDEX idx_reservas_profesor_id ON reservas(profesor_id);
CREATE INDEX idx_reservas_curso_id ON reservas(curso_id);
CREATE INDEX idx_usuarios_departamento_id ON usuarios(departamento_id);
CREATE INDEX idx_valoraciones_empresa_id ON valoraciones(empresa_id);
CREATE INDEX idx_valoraciones_usuario_id ON valoraciones(usuario_id);
CREATE INDEX idx_empresas_nombre_lower ON empresas(LOWER(nombre));
CREATE INDEX idx_empresas_ciudad_lower ON empresas(LOWER(ciudad));
CREATE INDEX idx_empresas_activa ON empresas(activa) WHERE activa = true;
CREATE INDEX idx_usuarios_activo ON usuarios(activo) WHERE activo = true;
CREATE INDEX idx_usuarios_rol ON usuarios(rol);
CREATE INDEX idx_cursos_activo ON cursos(activo) WHERE activo = true;
CREATE INDEX idx_plazas_curso_academico ON plazas(curso_academico);
CREATE INDEX idx_reservas_estado ON reservas(estado);
CREATE INDEX idx_comentarios_es_privado ON comentarios(es_privado);


-- ============================================================
-- CHECK CONSTRAINTS
-- ============================================================

ALTER TABLE valoraciones ADD CONSTRAINT chk_valoraciones_puntuacion CHECK (puntuacion >= 1 AND puntuacion <= 5);
ALTER TABLE plazas ADD CONSTRAINT chk_plazas_cantidad CHECK (cantidad > 0);
ALTER TABLE reservas ADD CONSTRAINT chk_reservas_cantidad CHECK (cantidad > 0);
ALTER TABLE reservas ADD CONSTRAINT chk_reservas_estado CHECK (estado IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA'));
ALTER TABLE usuarios ADD CONSTRAINT chk_usuarios_rol CHECK (rol IN ('PROFESOR', 'ALUMNO', 'ADMIN'));
ALTER TABLE cursos ADD CONSTRAINT chk_cursos_grado CHECK (grado IN ('MEDIO', 'SUPERIOR'));


-- ============================================================
-- DATOS DE PRUEBA
-- ============================================================

-- DEPARTAMENTOS
INSERT INTO departamentos (codigo, nombre, created_at, updated_at) VALUES
('INF', 'Informática y Comunicaciones', NOW(), NOW()),
('HOT', 'Hostelería y Turismo', NOW(), NOW()),
('ADM', 'Administración y Gestión', NOW(), NOW()),
('COM', 'Comercio y Marketing', NOW(), NOW()),
('SAN', 'Sanidad', NOW(), NOW());


-- CURSOS
INSERT INTO cursos (codigo, siglas, nombre, grado, departamento_id, activo, created_at, updated_at) VALUES
('IFC303', 'DAM', 'Desarrollo de Aplicaciones Multiplataforma', 'SUPERIOR', 1, true, NOW(), NOW()),
('IFC302', 'DAW', 'Desarrollo de Aplicaciones Web', 'SUPERIOR', 1, true, NOW(), NOW()),
('IFC301', 'ASIR', 'Administración de Sistemas Informáticos en Red', 'SUPERIOR', 1, true, NOW(), NOW()),
('IFC201', 'SMR', 'Sistemas Microinformáticos y Redes', 'MEDIO', 1, true, NOW(), NOW()),
('HOT301', 'DC', 'Dirección de Cocina', 'SUPERIOR', 2, true, NOW(), NOW()),
('HOT302', 'DSERV', 'Dirección de Servicios de Restauración', 'SUPERIOR', 2, true, NOW(), NOW()),
('HOT201', 'COC', 'Cocina y Gastronomía', 'MEDIO', 2, true, NOW(), NOW()),
('HOT202', 'SERV', 'Servicios en Restauración', 'MEDIO', 2, true, NOW(), NOW()),
('ADM301', 'AF', 'Administración y Finanzas', 'SUPERIOR', 3, true, NOW(), NOW()),
('ADM302', 'ADF', 'Asistencia a la Dirección', 'SUPERIOR', 3, true, NOW(), NOW()),
('ADM201', 'GA', 'Gestión Administrativa', 'MEDIO', 3, true, NOW(), NOW()),
('COM301', 'TCOM', 'Transporte y Logística', 'SUPERIOR', 4, true, NOW(), NOW()),
('COM302', 'MKT', 'Marketing y Publicidad', 'SUPERIOR', 4, true, NOW(), NOW()),
('COM201', 'ACT', 'Actividades Comerciales', 'MEDIO', 4, true, NOW(), NOW()),
('SAN301', 'LAB', 'Laboratorio Clínico y Biomédico', 'SUPERIOR', 5, true, NOW(), NOW()),
('SAN201', 'CAE', 'Cuidados Auxiliares de Enfermería', 'MEDIO', 5, true, NOW(), NOW());


-- USUARIOS (contraseña: test123)
INSERT INTO usuarios (nif, nombre, apellidos, email, password_hash, rol, departamento_id, activo, created_at, updated_at) VALUES
('12345678A', 'Juan', 'García López', 'juan.garcia@cifpvillaaguimes.es', '$2a$10$WLBdiW7AO9jQeLP/Qwa.ce4V/3znvNmErQ8cuLpLipHkEztXn07nu', 'PROFESOR', 1, true, NOW(), NOW()),
('23456789B', 'María', 'Rodríguez Pérez', 'maria.rodriguez@cifpvillaaguimes.es', '$2a$10$WLBdiW7AO9jQeLP/Qwa.ce4V/3znvNmErQ8cuLpLipHkEztXn07nu', 'PROFESOR', 1, true, NOW(), NOW()),
('34567890C', 'Carlos', 'Martínez Sánchez', 'carlos.martinez@cifpvillaaguimes.es', '$2a$10$WLBdiW7AO9jQeLP/Qwa.ce4V/3znvNmErQ8cuLpLipHkEztXn07nu', 'PROFESOR', 1, true, NOW(), NOW()),
('45678901D', 'Ana', 'Hernández Díaz', 'ana.hernandez@cifpvillaaguimes.es', '$2a$10$WLBdiW7AO9jQeLP/Qwa.ce4V/3znvNmErQ8cuLpLipHkEztXn07nu', 'PROFESOR', 2, true, NOW(), NOW()),
('56789012E', 'Pedro', 'López Ruiz', 'pedro.lopez@cifpvillaaguimes.es', '$2a$10$WLBdiW7AO9jQeLP/Qwa.ce4V/3znvNmErQ8cuLpLipHkEztXn07nu', 'PROFESOR', 2, true, NOW(), NOW()),
('67890123F', 'Laura', 'González Torres', 'laura.gonzalez@cifpvillaaguimes.es', '$2a$10$WLBdiW7AO9jQeLP/Qwa.ce4V/3znvNmErQ8cuLpLipHkEztXn07nu', 'PROFESOR', 3, true, NOW(), NOW()),
('78901234G', 'Miguel', 'Fernández Castro', 'miguel.fernandez@cifpvillaaguimes.es', '$2a$10$WLBdiW7AO9jQeLP/Qwa.ce4V/3znvNmErQ8cuLpLipHkEztXn07nu', 'PROFESOR', 4, true, NOW(), NOW()),
('89012345H', 'Elena', 'Sánchez Moreno', 'elena.sanchez@cifpvillaaguimes.es', '$2a$10$WLBdiW7AO9jQeLP/Qwa.ce4V/3znvNmErQ8cuLpLipHkEztXn07nu', 'PROFESOR', 5, true, NOW(), NOW()),
('11111111A', 'Pablo', 'Medina Alonso', 'pablo.medina@cifpvillaaguimes.es', '$2a$10$WLBdiW7AO9jQeLP/Qwa.ce4V/3znvNmErQ8cuLpLipHkEztXn07nu', 'ALUMNO', 1, true, NOW(), NOW()),
('22222222B', 'Lucía', 'Vega Romero', 'lucia.vega@cifpvillaaguimes.es', '$2a$10$WLBdiW7AO9jQeLP/Qwa.ce4V/3znvNmErQ8cuLpLipHkEztXn07nu', 'ALUMNO', 1, true, NOW(), NOW()),
('33333333C', 'Diego', 'Navarro Gil', 'diego.navarro@cifpvillaaguimes.es', '$2a$10$WLBdiW7AO9jQeLP/Qwa.ce4V/3znvNmErQ8cuLpLipHkEztXn07nu', 'ALUMNO', 1, true, NOW(), NOW()),
('44444444D', 'Sara', 'Jiménez Luna', 'sara.jimenez@cifpvillaaguimes.es', '$2a$10$WLBdiW7AO9jQeLP/Qwa.ce4V/3znvNmErQ8cuLpLipHkEztXn07nu', 'ALUMNO', 1, true, NOW(), NOW()),
('55555555E', 'Adrián', 'Ruiz Herrera', 'adrian.ruiz@cifpvillaaguimes.es', '$2a$10$WLBdiW7AO9jQeLP/Qwa.ce4V/3znvNmErQ8cuLpLipHkEztXn07nu', 'ALUMNO', 2, true, NOW(), NOW()),
('66666666F', 'Carmen', 'Morales Vidal', 'carmen.morales@cifpvillaaguimes.es', '$2a$10$WLBdiW7AO9jQeLP/Qwa.ce4V/3znvNmErQ8cuLpLipHkEztXn07nu', 'ALUMNO', 2, true, NOW(), NOW()),
('77777777G', 'Marcos', 'Ortega Ramos', 'marcos.ortega@cifpvillaaguimes.es', '$2a$10$WLBdiW7AO9jQeLP/Qwa.ce4V/3znvNmErQ8cuLpLipHkEztXn07nu', 'ALUMNO', 3, true, NOW(), NOW()),
('88888888H', 'Alba', 'Castro Vega', 'alba.castro@cifpvillaaguimes.es', '$2a$10$WLBdiW7AO9jQeLP/Qwa.ce4V/3znvNmErQ8cuLpLipHkEztXn07nu', 'ALUMNO', 5, true, NOW(), NOW());


-- EMPRESAS
INSERT INTO empresas (cif, nombre, direccion, ciudad, codigo_postal, telefono, email, web, persona_contacto, telefono_contacto, email_contacto, descripcion, activa, created_by, created_at, updated_at) VALUES
('B12345678', 'TechSolutions Canarias S.L.', 'C/ León y Castillo, 45, 2º', 'Las Palmas de Gran Canaria', '35003', '928123456', 'info@techsolutions.es', 'https://www.techsolutions.es', 'María Rodríguez', '666123456', 'maria@techsolutions.es', 'Empresa líder en desarrollo de software, aplicaciones móviles y soluciones cloud.', true, 1, NOW(), NOW()),
('B23456789', 'DataCenter Islas', 'Polígono Industrial Arinaga, Nave 15', 'Agüimes', '35118', '928456789', 'info@datacenterislas.com', 'https://www.datacenterislas.com', 'Pedro Alonso', '666456789', 'pedro@datacenterislas.com', 'Centro de datos con servicios de hosting, cloud computing y administración de sistemas.', true, 1, NOW(), NOW()),
('B34567890', 'AppDev Studio', 'C/ Mesa y López, 60, 3º', 'Las Palmas de Gran Canaria', '35006', '928678901', 'hello@appdevstudio.es', 'https://www.appdevstudio.es', 'Lucía Hernández', '666678901', 'lucia@appdevstudio.es', 'Startup especializada en desarrollo de apps móviles iOS/Android y diseño UX/UI.', true, 2, NOW(), NOW()),
('B45678901', 'CiberSeguridad GC', 'Av. Mesa y López, 15', 'Las Palmas de Gran Canaria', '35007', '928789012', 'contacto@ciberseguridadgc.es', 'https://www.ciberseguridadgc.es', 'Antonio Martín', '666789012', 'antonio@ciberseguridadgc.es', 'Consultoría de ciberseguridad, auditorías, pentesting y formación.', true, 1, NOW(), NOW()),
('B56789012', 'Web Canarias Digital', 'C/ Triana, 100', 'Las Palmas de Gran Canaria', '35002', '928890123', 'info@webcanarias.es', 'https://www.webcanarias.es', 'Sandra López', '666890123', 'sandra@webcanarias.es', 'Agencia de desarrollo web, e-commerce y marketing digital.', true, 2, NOW(), NOW()),
('B67890123', 'Hotel Gran Canaria Palace', 'Av. de las Canteras, 100', 'Las Palmas de Gran Canaria', '35010', '928234567', 'rrhh@grancanariapalace.com', 'https://www.grancanariapalace.com', 'Carlos Santana', '666234567', 'carlos@grancanariapalace.com', 'Hotel de 5 estrellas con restaurante galardonado, spa y centro de convenciones.', true, 4, NOW(), NOW()),
('B78901234', 'Restaurante El Marinero', 'Puerto de Mogán, s/n', 'Mogán', '35138', '928567890', 'reservas@elmarinero.es', 'https://www.elmarinero.es', 'José Medina', '666567890', 'jose@elmarinero.es', 'Restaurante especializado en cocina marinera canaria. 1 estrella Michelin.', true, 4, NOW(), NOW()),
('B89012345', 'Grupo Gastronómico Atlántico', 'C/ Pérez Galdós, 25', 'Las Palmas de Gran Canaria', '35002', '928012345', 'info@gastronomico-atlantico.com', 'https://www.gastronomico-atlantico.com', 'Elena Torres', '666012345', 'elena@gastronomico-atlantico.com', 'Grupo con 5 restaurantes de diferentes conceptos gastronómicos.', true, 5, NOW(), NOW()),
('B90123456', 'Hotel Lopesan Costa Meloneras', 'C/ Mar Mediterráneo, 1', 'San Bartolomé de Tirajana', '35100', '928143567', 'formacion@lopesan.com', 'https://www.lopesan.com', 'Marta González', '666143567', 'marta.gonzalez@lopesan.com', 'Resort de lujo con 1136 habitaciones, 5 restaurantes, spa y campo de golf.', true, 4, NOW(), NOW()),
('B01234567', 'Gestión Integral Canaria', 'C/ Triana, 22, 1º', 'Las Palmas de Gran Canaria', '35002', '928345678', 'contacto@gestionintegral.es', 'https://www.gestionintegral.es', 'Laura Pérez', '666345678', 'laura@gestionintegral.es', 'Asesoría fiscal, laboral y contable para PYMES y autónomos.', true, 6, NOW(), NOW()),
('B11223344', 'Consulting Atlántico', 'C/ Viera y Clavijo, 30', 'Las Palmas de Gran Canaria', '35002', '928223344', 'info@consultingatlantic.es', 'https://www.consultingatlantic.es', 'Fernando Ramos', '666223344', 'fernando@consultingatlantic.es', 'Consultoría de negocio, transformación digital y recursos humanos.', true, 6, NOW(), NOW()),
('B22334455', 'Logística Canaria Express', 'Polígono Industrial Arinaga, Nave 45', 'Agüimes', '35118', '928334455', 'info@logisticacanaria.es', 'https://www.logisticacanaria.es', 'Roberto Suárez', '666334455', 'roberto@logisticacanaria.es', 'Empresa de transporte y logística. Distribución en las islas.', true, 7, NOW(), NOW()),
('B33445566', 'Marketing Island', 'C/ Secretario Artiles, 10', 'Las Palmas de Gran Canaria', '35004', '928445566', 'hola@marketingisland.es', 'https://www.marketingisland.es', 'Patricia Díaz', '666445566', 'patricia@marketingisland.es', 'Agencia de marketing digital, branding y publicidad.', true, 7, NOW(), NOW()),
('B44556677', 'Laboratorios Canarios S.L.', 'C/ Tomás Morales, 85', 'Las Palmas de Gran Canaria', '35003', '928556677', 'info@labcanarios.es', 'https://www.labcanarios.es', 'Dr. Miguel Álvarez', '666556677', 'direccion@labcanarios.es', 'Laboratorio de análisis clínicos y biomédicos. Acreditado por ENAC.', true, 8, NOW(), NOW()),
('B55667788', 'Clínica Dental Sonrisa', 'Av. Marítima, 45', 'Las Palmas de Gran Canaria', '35003', '928667788', 'citas@clinicasonrisa.es', 'https://www.clinicasonrisa.es', 'Dra. Isabel Moreno', '666667788', 'direccion@clinicasonrisa.es', 'Clínica dental con 10 gabinetes, ortodoncia e implantes.', true, 8, NOW(), NOW()),
('B66778899', 'Hotel Resort & Tech', 'Av. del Mar, 50', 'Maspalomas', '35100', '928778899', 'info@hoteltech.com', 'https://www.hoteltech.com', 'Antonio Ruiz', '666778899', 'antonio@hoteltech.com', 'Hotel con sistema de domótica propio. Buscan perfiles técnicos y hostelería.', true, 1, NOW(), NOW());


-- EMPRESA-CURSOS
INSERT INTO empresa_cursos (empresa_id, curso_id, created_at) VALUES
(1, 1, NOW()), (1, 2, NOW()), (1, 3, NOW()),
(2, 3, NOW()), (2, 4, NOW()),
(3, 1, NOW()), (3, 2, NOW()),
(4, 3, NOW()), (4, 4, NOW()),
(5, 2, NOW()), (5, 4, NOW()),
(6, 5, NOW()), (6, 6, NOW()), (6, 7, NOW()), (6, 8, NOW()),
(7, 5, NOW()), (7, 7, NOW()),
(8, 5, NOW()), (8, 6, NOW()), (8, 7, NOW()), (8, 8, NOW()),
(9, 5, NOW()), (9, 6, NOW()), (9, 7, NOW()), (9, 8, NOW()),
(10, 9, NOW()), (10, 10, NOW()), (10, 11, NOW()),
(11, 9, NOW()), (11, 10, NOW()),
(12, 12, NOW()), (12, 14, NOW()),
(13, 13, NOW()), (13, 14, NOW()),
(14, 15, NOW()),
(15, 16, NOW()),
(16, 1, NOW()), (16, 3, NOW()), (16, 4, NOW()), (16, 5, NOW()), (16, 7, NOW());


-- EMPRESA CONTACTADA
INSERT INTO empresa_contactada (empresa_id, departamento_id, profesor_id, fecha, notas, created_at, updated_at) VALUES
(1, 1, 1, '2025-01-15', 'Muy interesados en alumnos de DAM. Piden conocimientos de React.', NOW(), NOW()),
(2, 1, 1, '2025-01-20', 'Confirman 4 plazas para ASIR. Turno de mañana.', NOW(), NOW()),
(3, 1, 2, '2025-01-22', 'Startup dinámica. Posibilidad de contratación.', NOW(), NOW()),
(4, 1, 1, '2025-01-25', 'Buscan alumnos de ASIR para SOC. Valorable inglés B2.', NOW(), NOW()),
(5, 1, 2, '2025-01-28', 'Necesitan desarrolladores web. Trabajo híbrido posible.', NOW(), NOW()),
(6, 2, 4, '2025-01-10', 'Confirman plazas para cocina y sala. Buen ambiente.', NOW(), NOW()),
(7, 2, 4, '2025-01-12', 'Estrella Michelin. Exigente pero muy formativo.', NOW(), NOW()),
(8, 2, 5, '2025-01-14', '5 restaurantes. Rotación por diferentes conceptos.', NOW(), NOW()),
(9, 2, 4, '2025-01-18', 'Cadena Lopesan. Muchas oportunidades de crecimiento.', NOW(), NOW()),
(10, 3, 6, '2025-01-08', 'Buscan perfiles con Excel avanzado. Horario flexible.', NOW(), NOW()),
(11, 3, 6, '2025-01-16', 'Ofrecen formación interna en SAP. Valorable inglés.', NOW(), NOW()),
(12, 4, 7, '2025-02-01', 'Necesitan perfiles para almacén. Carnet B necesario.', NOW(), NOW()),
(13, 4, 7, '2025-02-05', 'Buscan creativos para redes sociales.', NOW(), NOW()),
(14, 5, 8, '2025-01-30', 'Buscan alumnos metódicos. Material proporcionado.', NOW(), NOW()),
(15, 5, 8, '2025-02-02', 'Ofrecen formación en software dental. Buen ambiente.', NOW(), NOW()),
(16, 1, 1, '2025-01-18', 'Buscan técnicos para sistema domótico.', NOW(), NOW());


-- COMENTARIOS
INSERT INTO comentarios (empresa_id, usuario_id, texto, es_privado, created_at, updated_at) VALUES
(1, 1, 'Excelente empresa para hacer prácticas. Los tutores son muy profesionales.', false, NOW(), NOW()),
(1, 9, 'Hice mis prácticas aquí. Muy recomendable, me enseñaron React.', false, NOW(), NOW()),
(2, 1, 'DataCenter muy bien equipado. Los alumnos aprenden infraestructura real.', false, NOW(), NOW()),
(3, 10, 'Startup con muy buen ambiente. Trabajo en equipo constante.', false, NOW(), NOW()),
(6, 4, 'Hotel de referencia. Los alumnos rotan por diferentes departamentos.', false, NOW(), NOW()),
(7, 13, 'Restaurante exigente pero se aprende muchísimo.', false, NOW(), NOW()),
(9, 5, 'Lopesan ofrece muy buenas condiciones. Posibilidad de quedarse.', false, NOW(), NOW()),
(10, 6, 'Asesoría muy completa. Los alumnos ven casos reales.', false, NOW(), NOW()),
(1, 2, 'OJO: Piden conocimientos previos de React Native. Filtrar candidatos.', true, NOW(), NOW()),
(4, 1, 'Director técnico exigente. Solo alumnos motivados con buen inglés.', true, NOW(), NOW()),
(7, 4, 'El Marinero exige mucho compromiso. Evitar alumnos impuntuales.', true, NOW(), NOW()),
(9, 5, 'Lopesan ha tenido problemas con turno de noche. Preferir día.', true, NOW(), NOW()),
(14, 8, 'El laboratorio requiere certificado de vacunación.', true, NOW(), NOW());


-- VALORACIONES
INSERT INTO valoraciones (empresa_id, usuario_id, puntuacion, created_at, updated_at) VALUES
(1, 1, 5, NOW(), NOW()), (1, 2, 5, NOW(), NOW()), (1, 9, 5, NOW(), NOW()), (1, 10, 4, NOW(), NOW()),
(2, 1, 5, NOW(), NOW()), (2, 11, 5, NOW(), NOW()),
(3, 2, 4, NOW(), NOW()), (3, 10, 5, NOW(), NOW()),
(4, 1, 4, NOW(), NOW()),
(5, 2, 4, NOW(), NOW()),
(6, 4, 5, NOW(), NOW()), (6, 13, 4, NOW(), NOW()),
(7, 4, 5, NOW(), NOW()), (7, 13, 5, NOW(), NOW()),
(8, 5, 4, NOW(), NOW()),
(9, 4, 5, NOW(), NOW()), (9, 5, 4, NOW(), NOW()), (9, 14, 5, NOW(), NOW()),
(10, 6, 4, NOW(), NOW()),
(11, 6, 4, NOW(), NOW()),
(12, 7, 4, NOW(), NOW()),
(13, 7, 5, NOW(), NOW()),
(14, 8, 5, NOW(), NOW()),
(15, 8, 4, NOW(), NOW()),
(16, 1, 4, NOW(), NOW()), (16, 4, 4, NOW(), NOW());


-- FAVORITOS
INSERT INTO favoritos (usuario_id, empresa_id, created_at) VALUES
(1, 1, NOW()), (1, 2, NOW()), (1, 4, NOW()),
(2, 1, NOW()), (2, 3, NOW()), (2, 5, NOW()),
(4, 6, NOW()), (4, 7, NOW()), (4, 9, NOW()),
(6, 10, NOW()), (6, 11, NOW()),
(9, 1, NOW()), (9, 3, NOW()),
(10, 1, NOW()), (10, 3, NOW()), (10, 5, NOW()),
(11, 2, NOW()), (11, 4, NOW()),
(13, 6, NOW()), (13, 7, NOW()), (13, 9, NOW()),
(15, 10, NOW());


-- LISTAS
INSERT INTO listas (nombre, descripcion, es_favoritos, usuario_id, created_at, updated_at) VALUES
('FCT 2025 - DAM', 'Empresas seleccionadas para alumnos de DAM', false, 1, NOW(), NOW()),
('Empresas contactar marzo', 'Pendiente de llamar', false, 1, NOW(), NOW()),
('Desarrollo Web', 'Empresas especializadas en desarrollo web', false, 2, NOW(), NOW()),
('Top Restaurantes', 'Mejores restaurantes para FCT de cocina', false, 4, NOW(), NOW()),
('Hoteles 5 estrellas', 'Hoteles de alto standing', false, 4, NOW(), NOW()),
('Mis favoritas', 'Empresas donde me gustaría hacer prácticas', false, 9, NOW(), NOW()),
('Para investigar', 'Empresas que tengo que mirar mejor', false, 10, NOW(), NOW());


-- LISTA-EMPRESAS
INSERT INTO lista_empresas (lista_id, empresa_id, notas, created_at) VALUES
(1, 1, 'Primera opción. 3 plazas confirmadas.', NOW()),
(1, 3, 'Startup interesante. 2 plazas.', NOW()),
(1, 16, 'Solo para alumnos con interés en IoT.', NOW()),
(2, 4, 'Llamar a Antonio el lunes 3 de marzo.', NOW()),
(2, 5, 'Sandra pidió que la llamara primera semana de marzo.', NOW()),
(3, 1, NULL, NOW()),
(3, 3, NULL, NOW()),
(3, 5, NULL, NOW()),
(4, 7, 'Estrella Michelin. Solo los mejores alumnos.', NOW()),
(4, 8, 'Grupo con varios conceptos. Muy formativo.', NOW()),
(5, 6, NULL, NOW()),
(5, 9, 'Cadena Lopesan. Muchas oportunidades.', NOW()),
(6, 1, 'La mejor para desarrollo móvil', NOW()),
(6, 3, 'Me gustaría trabajar en una startup', NOW()),
(7, 2, 'Mirar qué tecnologías usan', NOW()),
(7, 4, 'Preguntar por el tema del inglés', NOW()),
(7, 5, 'Ver portfolio de proyectos', NOW());


-- PLAZAS
INSERT INTO plazas (empresa_id, departamento_id, curso_id, cantidad, es_general, curso_academico, created_by, created_at, updated_at) VALUES
(1, 1, 1, 3, false, '2024-2025', 1, NOW(), NOW()),
(1, 1, 2, 2, false, '2024-2025', 1, NOW(), NOW()),
(2, 1, 3, 3, false, '2024-2025', 1, NOW(), NOW()),
(2, 1, 4, 2, false, '2024-2025', 1, NOW(), NOW()),
(3, 1, 1, 2, false, '2024-2025', 2, NOW(), NOW()),
(3, 1, 2, 2, false, '2024-2025', 2, NOW(), NOW()),
(4, 1, 3, 2, false, '2024-2025', 1, NOW(), NOW()),
(5, 1, 2, 3, false, '2024-2025', 2, NOW(), NOW()),
(6, 2, NULL, 5, true, '2024-2025', 4, NOW(), NOW()),
(7, 2, 5, 2, false, '2024-2025', 4, NOW(), NOW()),
(7, 2, 7, 2, false, '2024-2025', 4, NOW(), NOW()),
(8, 2, NULL, 6, true, '2024-2025', 5, NOW(), NOW()),
(9, 2, 5, 4, false, '2024-2025', 4, NOW(), NOW()),
(9, 2, 7, 4, false, '2024-2025', 4, NOW(), NOW()),
(9, 2, 8, 3, false, '2024-2025', 4, NOW(), NOW()),
(10, 3, NULL, 4, true, '2024-2025', 6, NOW(), NOW()),
(11, 3, 9, 2, false, '2024-2025', 6, NOW(), NOW()),
(12, 4, 12, 3, false, '2024-2025', 7, NOW(), NOW()),
(13, 4, 13, 2, false, '2024-2025', 7, NOW(), NOW()),
(13, 4, 14, 2, false, '2024-2025', 7, NOW(), NOW()),
(14, 5, 15, 3, false, '2024-2025', 8, NOW(), NOW()),
(15, 5, 16, 2, false, '2024-2025', 8, NOW(), NOW()),
(16, 1, NULL, 3, true, '2024-2025', 1, NOW(), NOW()),
(16, 2, NULL, 4, true, '2024-2025', 4, NOW(), NOW());


-- RESERVAS
INSERT INTO reservas (plaza_id, curso_id, profesor_id, cantidad, clase, estado, notas, created_at, updated_at) VALUES
(1, 1, 1, 2, '2º DAM A', 'CONFIRMADA', 'Pablo Medina y Lucía Vega', NOW(), NOW()),
(3, 3, 1, 2, '2º ASIR', 'CONFIRMADA', 'Diego Navarro y otro por confirmar', NOW(), NOW()),
(5, 1, 2, 1, '2º DAM B', 'CONFIRMADA', 'Alumno interesado en startups', NOW(), NOW()),
(10, 5, 4, 2, '2º DC', 'CONFIRMADA', 'Mejores alumnos de cocina', NOW(), NOW()),
(13, 5, 4, 2, '2º DC', 'CONFIRMADA', 'Lopesan - turno mañana', NOW(), NOW()),
(16, 9, 6, 2, '2º AF', 'CONFIRMADA', 'Gestión Integral', NOW(), NOW()),
(2, 2, 1, 1, '2º DAW', 'PENDIENTE', 'Esperando confirmación de TechSolutions', NOW(), NOW()),
(6, 2, 2, 2, '2º DAW', 'PENDIENTE', 'Pendiente entrevista con Sandra', NOW(), NOW()),
(12, 7, 5, 2, '2º COC', 'PENDIENTE', 'Grupo Gastronómico - rotación', NOW(), NOW()),
(18, 12, 7, 2, '2º TCOM', 'PENDIENTE', 'Logística Canaria', NOW(), NOW()),
(21, 15, 8, 2, '2º LAB', 'PENDIENTE', 'Laboratorios Canarios', NOW(), NOW()),
(7, 3, 1, 1, '2º ASIR', 'CANCELADA', 'El alumno se dio de baja del ciclo', NOW(), NOW());


-- ============================================================
-- FIN DEL SCRIPT
-- ============================================================
-- CREDENCIALES DE PRUEBA:
-- Todos los usuarios: test123
--
-- Profesores:
--   juan.garcia@cifpvillaaguimes.es
--   maria.rodriguez@cifpvillaaguimes.es
--   carlos.martinez@cifpvillaaguimes.es
--   ana.hernandez@cifpvillaaguimes.es
--   pedro.lopez@cifpvillaaguimes.es
--   laura.gonzalez@cifpvillaaguimes.es
--   miguel.fernandez@cifpvillaaguimes.es
--   elena.sanchez@cifpvillaaguimes.es
--
-- Alumnos:
--   pablo.medina@cifpvillaaguimes.es
--   lucia.vega@cifpvillaaguimes.es
--   diego.navarro@cifpvillaaguimes.es
--   sara.jimenez@cifpvillaaguimes.es
--   adrian.ruiz@cifpvillaaguimes.es
--   carmen.morales@cifpvillaaguimes.es
--   marcos.ortega@cifpvillaaguimes.es
--   alba.castro@cifpvillaaguimes.es
-- ============================================================
